[package]
name = "io_buffer_ext"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7", features = ["rb-sys"] }
rb-sys = { version = "0.9" }
alloca = { version = "0.4.0" }
